name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build ./HEH_BE/Exadel.HEH.Backend.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./HEH_BE/Exadel.HEH.Backend.sln --configuration Release
